live_config_reload = true

import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/ashes-dark.toml"
  #"~/.config/alacritty/dracula.toml"
]

[colors.primary]
#foreground = "#c5c8c6"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "IosevkaTerm NF"
#family = "MesloLGS NF"
style = "Regular"

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/fish"

[window]
opacity = 0.75
blur = true

[window.dimensions]
columns = 135
lines = 35
