live_config_reload = true

[colors.primary]
foreground = "#c5c8c6"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "IosevkaTerm NF"
#family = "MesloLGS NF"
style = "Regular"

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/fish"

[window]
opacity = 0.65
blur = true

[window.dimensions]
columns = 135
lines = 35
