
[colors.primary]
#foreground = "#c5c8c6"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.normal]
family = "IosevkaTerm NF"
#family = "Anka/Coder Narrow"
style = "Light Condensed"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/fish"

[window]
opacity = 0.70
blur = true
padding.x = 5
padding.y =5
dynamic_title = true

[window.dimensions]
columns = 135
lines = 35

[general]
live_config_reload = true

import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/ashes-dark.toml"
  #"~/.config/alacritty/dracula.toml"
]

[terminal]
